/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group ovs --version v1beta1 --kind OVS --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// OvsDefaults -
type OvsDefaults struct {
	OvsContainerImageURL string
	OvnContainerImageURL string
}

var ovsDefaults OvsDefaults

// log is for logging in this package.
var ovslog = logf.Log.WithName("ovs-resource")

// SetupOvsDefaults - initialize Ovs spec defaults for use with either internal or external webhooks
func SetupOvsDefaults(defaults OvsDefaults) {
	ovsDefaults = defaults
	ovslog.Info("OVS defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *OVS) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-ovs-openstack-org-v1beta1-ovs,mutating=true,failurePolicy=fail,sideEffects=None,groups=ovs.openstack.org,resources=ovs,verbs=create;update,versions=v1beta1,name=movs.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &OVS{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *OVS) Default() {
	ovslog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this OVS spec
func (spec *OVSSpec) Default() {
	if spec.OvsContainerImage == "" {
		spec.OvsContainerImage = ovsDefaults.OvsContainerImageURL
	}
	if spec.OvnContainerImage == "" {
		spec.OvnContainerImage = ovsDefaults.OvnContainerImageURL
	}
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-ovs-openstack-org-v1beta1-ovs,mutating=false,failurePolicy=fail,sideEffects=None,groups=ovs.openstack.org,resources=ovs,verbs=create;update,versions=v1beta1,name=vovs.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &OVS{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *OVS) ValidateCreate() error {
	ovslog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *OVS) ValidateUpdate(old runtime.Object) error {
	ovslog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *OVS) ValidateDelete() error {
	ovslog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil
}
